name: Keep Hugging Face Alive

on:
  schedule:
    # Jalan setiap 4 jam sekali
    - cron: "0 */4 * * *"
  workflow_dispatch: # Supaya bisa dijalankan manual juga

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping HF Space
        run: |
          # Ganti URL di bawah dengan URL Hugging Face Anda
          curl -I https://calluu-predict2.hf.space
